### PR TITLE
Homeassistant mqtt discovery, wip

### PR DESCRIPTION
**Pull request by kng**
Working, WIP, some hardcoded stuff left.
Squash the merge to a new branch.

### CODE REVIEW

**Comment by dagbdagb** [comment]
Looking forward to this!

**Comment by Isaksson** [comment]
@kng What is the status with the implementation?
I am using OpenHAB as home automation system but today I installed Home Assistant just to see what its like on the other side :)
So my plan was to try out the Energy functions in HA.

**Comment by Isaksson** [comment]
> > @kng What is the status with the implementation?
> 
> The code works so you can easily fetch my branch and compile it.
> 
Thanks for the information.
I think I will wait until I have some more skills with Home Assistant, I added the "power" and "total_increasing" manually in yaml so now I have data in my energy dashboard, but it would be a nice feature with the auto discover.

**Comment by gskjold** [comment]
Finally had some breathing room to look at this. To me this looks pretty clean and works as advertised as far as I can tell. There have not been any change last month, so I'm assuming it runs smoothly for you @kng ? What was your hardware setup again? 

It did not run properly on ESP8266, so I made some adjustments to reduce stack size, mostly same changes as for v2.0.10.

Did some minor changes in the code and made adjustment to only send autodiscovery once, with retain flag.

**Comment by kng** [comment]
Yes, I have had this running smoothly over the last month on a esp32. Build based on the WDT stuff, so around 2.0.3 I guess ?
Haven't had time to mess with it, very nice that you put the effort in, I shall fetch the pr-172 branch and try it out in the near future.

Todo: show the values used on the mqtt config page

Todo: figure out if the [discovery topic](https://github.com/gskjold/AmsToMqttBridge/blob/pr-172/src/mqtt/HomeAssistantMqttHandler.cpp#L250) structure is appropriate, maybe add a '/' level to make it into a cleaner structure.
Perhaps: homeassistant/sensor/**amsreader**/ams-3a08_rssi

**Pull request merged**
