### PR TITLE
Libdeps updated to avoid conflict with time.h

### PR DESCRIPTION
**Pull request by kng**
Was unable to build, a lot of errors on time() functions.
Resolved with comment in https://github.com/PaulStoffregen/Time/releases/tag/v1.6.1
Also fixed warning on hexutils include.

### CODE REVIEW

**Comment by gskjold** [comment]
Thanks for the cleanup, good work!

**Comment by gskjold** [comment]
Will not build with Time@1.6.1. 
https://github.com/gskjold/AmsToMqttBridge/runs/4569617712?check_suite_focus=true

Also, will not build with Timezone lib from github as it is scoped to avr: https://github.com/JChristensen/Timezone/blob/7cf1425b4ee598573e85b6fa124d4514f71c2586/library.properties#L9

Lib changes had to be reverted..

**Comment by kng** [comment]
Oh, perhaps need to change the includes to: #include "TimeLib.h"

**Comment by gskjold** [comment]
That was exactly right, thanks

**Pull request merged**
